### ISSUE TITLE
可以分享一下数据集吗

### ISSUE THREAD

**Issue by YJCstar** [geniaofengyue4639/RubbishClassify#1]

**Comment by geniaofengyue4639** [comment]
https://aistudio.baidu.com/datasetdetail/16284
应该是这个数据集




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geniaofengyue4639/RubbishClassify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月22日(星期五) 上午10:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[geniaofengyue4639/RubbishClassify] 可以分享一下数据集吗 (Issue #1)

**Comment by YJCstar** [comment]
感谢你😍

歌鸟风月 ***@***.***> 于 2024年3月23日周六 10:56写道：

**Comment by geniaofengyue4639** [comment]
https://aistudio.baidu.com/datasetdetail/16284
应该是这个数据集

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geniaofengyue4639/RubbishClassify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月22日(星期一) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geniaofengyue4639/RubbishClassify] 可以分享一下数据集吗 (Issue #1)





 
Closed #1 as completed.
